name: Bug Report (Form)
description: File a bug report through a simplified form
title: "[MC Version]: "
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!
        Keep in mind that this board is **only for issues**! If you have a **suggestion**, please use the **Discussions** tab instead.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please explain in detail what the issue is.
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to reproduce
      description: Which steps did you take to cause the issue? Please describe below how to replicate it.
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: | 
        Please provide the client or server logs from your launcher. They contain vital information to troubleshoot the issue.
        To upload logs, you can use websites such as: https://pastebin.com/ https://paste.ee/ https://mclo.gs/
  - type: textarea
    id: mod_list
    attributes:
      label: Mod List
      description: |
        Please provide the list of mods you're using, especially the versions of Forge and Farmer's Delight.
        You can generate a mod list by forcing a crash. In your game, hold F3+C for 10 seconds, then check your logs; the list of mods will be by the end.
  - type: checkboxes
    id: has_tested_minimal_instance
    attributes:
      label: Minimal instance
      description: Have you tried testing the issue on a Minecraft instance with only Farmer's Delight installed?
      options:
        - label: I have tested this on a minimal instance
  - type: checkboxes
    id: has_performance_mods
    attributes:
      label: Performance and shader mods
      description: Sometimes, performance and shader mods (for example, Optifine, Iris etc.) can cause unpredictable problems. Have you tested this issue without those installed?
      options:
        - label: I have tested this without performance or shader mods